import type { ModuleDefinition, ResourceDefinition, SelectOption } from '@/types/operations'

const paymentOptions: SelectOption[] = [
  { title: 'Efectivo', value: 'cash' },
  { title: 'Tarjeta', value: 'card' },
  { title: 'Transferencia', value: 'transfer' },
  { title: 'Otro', value: 'other' },
]

const movementOptions: SelectOption[] = [
  { title: 'Entrada', value: 'entry' },
  { title: 'Salida', value: 'exit' },
  { title: 'Ajuste de entrada', value: 'adjustment_in' },
  { title: 'Ajuste de salida', value: 'adjustment_out' },
  { title: 'Consumo', value: 'consumption' },
  { title: 'Devolución de entrada', value: 'return_in' },
  { title: 'Devolución de salida', value: 'return_out' },
]

const transactionTypeOptions: SelectOption[] = [
  { title: 'Ingreso', value: 'income' },
  { title: 'Egreso', value: 'expense' },
]

const sourceOptions: SelectOption[] = [
  { title: 'Manual', value: 'manual' },
  { title: 'Venta', value: 'sale' },
  { title: 'Compra', value: 'purchase' },
  { title: 'Reembolso', value: 'refund' },
  { title: 'Ajuste', value: 'adjustment' },
  { title: 'Otro', value: 'other' },
]

const customerResource: ResourceDefinition = {
  key: 'customers',
  title: 'Clientes',
  singular: 'cliente',
  icon: 'mdi-account-group-outline',
  description: 'Directorio comercial, contacto, búsqueda y estado del cliente.',
  listPath: '/customers',
  createPath: '/customers',
  updatePath: '/customers/{id}',
  updateMethod: 'put',
  columns: [
    { key: 'first_name', label: 'Nombres' },
    { key: 'last_name', label: 'Apellidos' },
    { key: 'document_number', label: 'Documento' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'email', label: 'Correo' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'first_name', label: 'Nombres', required: true },
    { key: 'last_name', label: 'Apellidos', required: true },
    { key: 'document_number', label: 'Documento' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'email', label: 'Correo', kind: 'email' },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 3 },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true, editOnly: true },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const serviceResource: ResourceDefinition = {
  key: 'services',
  title: 'Servicios',
  singular: 'servicio',
  icon: 'mdi-content-cut',
  description: 'Catálogo de servicios, duración operativa, precio y disponibilidad.',
  listPath: '/services/company/{company_id}',
  createPath: '/services',
  updatePath: '/services/{id}',
  updateMethod: 'put',
  deletePath: '/services/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'name', label: 'Servicio' },
    { key: 'duration_minutes', label: 'Duración' },
    { key: 'price', label: 'Precio', format: 'money' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 3 },
    { key: 'duration_minutes', label: 'Duración en minutos', kind: 'number', required: true },
    { key: 'price', label: 'Precio', kind: 'number', required: true },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
    { key: 'company_id', label: 'Empresa', companyFromSession: true, createOnly: true },
  ],
}

const salesResource: ResourceDefinition = {
  key: 'sales',
  title: 'Ventas y POS',
  singular: 'venta',
  icon: 'mdi-point-of-sale',
  description: 'Venta mixta de productos y servicios, pagos y comprobantes.',
  listPath: '/sales',
  createPath: '/sales',
  columns: [
    { key: 'sale_number', label: 'Venta' },
    { key: 'customer_name', label: 'Cliente' },
    { key: 'total_amount', label: 'Total', format: 'money' },
    { key: 'paid_amount', label: 'Pagado', format: 'money' },
    { key: 'status', label: 'Estado', format: 'status' },
    { key: 'sold_at', label: 'Fecha', format: 'datetime' },
  ],
  fields: [
    { key: 'sale_number', label: 'Número de venta', required: true },
    {
      key: 'customer_id',
      label: 'Cliente',
      kind: 'select',
      optionsPath: '/customers?limit=100&is_active=true',
      optionLabelKeys: ['first_name', 'last_name'],
    },
    {
      key: 'cash_session_id',
      label: 'Sesión de caja',
      kind: 'select',
      required: true,
      optionsPath: '/cash-register/sessions?limit=100&status=open',
      optionLabelKeys: ['id'],
    },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
    {
      key: 'details',
      label: 'Detalles de productos y servicios',
      kind: 'json',
      required: true,
      defaultValue: [
        {
          item_type: 'service',
          service_id: '',
          quantity: '1.000',
          unit_price: null,
          discount_amount: '0.00',
          tax_rate: '0.00',
        },
      ],
      help: 'Arreglo de detalles. Use item_type product o service y su UUID correspondiente.',
      rows: 9,
    },
    {
      key: 'payments',
      label: 'Pagos',
      kind: 'json',
      required: true,
      defaultValue: [
        { payment_method: paymentOptions[0]?.value, amount: '0.00', tendered_amount: null },
      ],
      help: 'Métodos admitidos: cash, card, transfer y other.',
      rows: 6,
    },
  ],
  actions: [
    {
      key: 'receipt',
      label: 'PDF',
      icon: 'mdi-file-pdf-box',
      color: 'error',
      method: 'get',
      path: '/sales/{id}/receipt.pdf',
      download: true,
    },
    {
      key: 'email',
      label: 'Correo',
      icon: 'mdi-email-outline',
      method: 'post',
      path: '/sales/{id}/receipt/email',
      fields: [
        { key: 'recipient_email', label: 'Correo destinatario', kind: 'email' },
        { key: 'subject', label: 'Asunto' },
        { key: 'message', label: 'Mensaje', kind: 'textarea', rows: 3 },
      ],
    },
    {
      key: 'whatsapp',
      label: 'WhatsApp',
      icon: 'mdi-whatsapp',
      color: 'success',
      method: 'post',
      path: '/sales/{id}/receipt/whatsapp',
      fields: [
        { key: 'phone_number', label: 'Número con indicativo', required: true },
        { key: 'message', label: 'Mensaje', kind: 'textarea', rows: 3 },
      ],
    },
    {
      key: 'cancel',
      label: 'Cancelar',
      icon: 'mdi-cancel',
      color: 'error',
      method: 'post',
      path: '/sales/{id}/cancel',
      fields: [{ key: 'reason', label: 'Motivo', kind: 'textarea', required: true, rows: 3 }],
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const categoryResource: ResourceDefinition = {
  key: 'categories',
  title: 'Categorías',
  singular: 'categoría',
  icon: 'mdi-shape-outline',
  description: 'Clasificación del catálogo de productos.',
  listPath: '/inventory/categories',
  createPath: '/inventory/categories',
  updatePath: '/inventory/categories/{id}',
  updateMethod: 'patch',
  deletePath: '/inventory/categories/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'name', label: 'Categoría' },
    { key: 'description', label: 'Descripción' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 3 },
    { key: 'is_active', label: 'Activa', kind: 'switch', defaultValue: true },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const productResource: ResourceDefinition = {
  key: 'products',
  title: 'Productos',
  singular: 'producto',
  icon: 'mdi-package-variant-closed',
  description: 'Catálogo, costos, precios, existencias y niveles de stock.',
  listPath: '/inventory/products',
  createPath: '/inventory/products',
  updatePath: '/inventory/products/{id}',
  updateMethod: 'patch',
  deletePath: '/inventory/products/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'code', label: 'Código' },
    { key: 'name', label: 'Producto' },
    { key: 'current_stock', label: 'Existencia' },
    { key: 'minimum_stock', label: 'Mínimo' },
    { key: 'sale_price', label: 'Venta', format: 'money' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    {
      key: 'category_id',
      label: 'Categoría',
      kind: 'select',
      required: true,
      optionsPath: '/inventory/categories?limit=100&is_active=true',
      optionLabelKeys: ['name'],
    },
    { key: 'code', label: 'Código', required: true },
    { key: 'barcode', label: 'Código de barras' },
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 2 },
    { key: 'purchase_price', label: 'Costo', kind: 'number', defaultValue: '0.00' },
    { key: 'sale_price', label: 'Precio de venta', kind: 'number', defaultValue: '0.00' },
    { key: 'current_stock', label: 'Existencia inicial', kind: 'number', defaultValue: '0.000' },
    { key: 'minimum_stock', label: 'Stock mínimo', kind: 'number', defaultValue: '0.000' },
    { key: 'maximum_stock', label: 'Stock máximo', kind: 'number' },
    { key: 'unit', label: 'Unidad', defaultValue: 'unit' },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const movementResource: ResourceDefinition = {
  key: 'movements',
  title: 'Movimientos',
  singular: 'movimiento',
  icon: 'mdi-swap-horizontal-bold',
  description: 'Entradas, salidas, ajustes, consumos y devoluciones.',
  listPath: '/inventory/movements',
  createPath: '/inventory/movements',
  columns: [
    { key: 'movement_type', label: 'Tipo', format: 'status' },
    { key: 'reference', label: 'Referencia' },
    { key: 'reason', label: 'Motivo' },
    { key: 'created_at', label: 'Fecha', format: 'datetime' },
    { key: 'details', label: 'Detalles', format: 'count' },
  ],
  fields: [
    {
      key: 'movement_type',
      label: 'Tipo',
      kind: 'select',
      options: movementOptions,
      required: true,
    },
    { key: 'reference', label: 'Referencia' },
    { key: 'reason', label: 'Motivo', required: true },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
    {
      key: 'details',
      label: 'Productos del movimiento',
      kind: 'json',
      required: true,
      defaultValue: [{ product_id: '', quantity: '1.000', unit_cost: null }],
      help: 'Agregue product_id, quantity y unit_cost cuando corresponda.',
      rows: 7,
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const registerResource: ResourceDefinition = {
  key: 'registers',
  title: 'Cajas',
  singular: 'caja',
  icon: 'mdi-cash-register',
  description: 'Puntos de caja disponibles para la operación.',
  listPath: '/cash-register/registers',
  createPath: '/cash-register/registers',
  updatePath: '/cash-register/registers/{id}',
  updateMethod: 'patch',
  deletePath: '/cash-register/registers/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'code', label: 'Código' },
    { key: 'name', label: 'Caja' },
    { key: 'description', label: 'Descripción' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'code', label: 'Código', required: true },
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 2 },
    { key: 'is_active', label: 'Activa', kind: 'switch', defaultValue: true },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const sessionResource: ResourceDefinition = {
  key: 'sessions',
  title: 'Sesiones',
  singular: 'sesión',
  icon: 'mdi-lock-clock',
  description: 'Apertura, seguimiento, resumen y cierre de caja.',
  listPath: '/cash-register/sessions',
  createPath: '/cash-register/sessions/open',
  columns: [
    { key: 'cash_register_id', label: 'Caja' },
    { key: 'status', label: 'Estado', format: 'status' },
    { key: 'opening_amount', label: 'Apertura', format: 'money' },
    { key: 'opened_at', label: 'Abierta', format: 'datetime' },
    { key: 'closed_at', label: 'Cerrada', format: 'datetime' },
  ],
  fields: [
    {
      key: 'cash_register_id',
      label: 'Caja',
      kind: 'select',
      required: true,
      optionsPath: '/cash-register/registers?limit=100&is_active=true',
      optionLabelKeys: ['code', 'name'],
    },
    { key: 'opening_amount', label: 'Monto inicial', kind: 'number', defaultValue: '0.00' },
    { key: 'opening_notes', label: 'Observaciones', kind: 'textarea', rows: 2 },
  ],
  actions: [
    {
      key: 'summary',
      label: 'Resumen',
      icon: 'mdi-calculator-variant-outline',
      method: 'get',
      path: '/cash-register/sessions/{id}/summary',
    },
    {
      key: 'close',
      label: 'Cerrar',
      icon: 'mdi-lock-outline',
      color: 'warning',
      method: 'post',
      path: '/cash-register/sessions/{id}/close',
      fields: [
        { key: 'counted_amount', label: 'Monto contado', kind: 'number', required: true },
        { key: 'closing_notes', label: 'Observaciones', kind: 'textarea', rows: 2 },
      ],
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const transactionResource: ResourceDefinition = {
  key: 'transactions',
  title: 'Transacciones',
  singular: 'transacción',
  icon: 'mdi-cash-sync',
  description: 'Ingresos y egresos manuales o vinculados a otros módulos.',
  listPath: '/cash-register/transactions',
  createPath: '/cash-register/sessions/{cash_session_id}/transactions',
  columns: [
    { key: 'transaction_type', label: 'Tipo', format: 'status' },
    { key: 'source', label: 'Origen', format: 'status' },
    { key: 'amount', label: 'Valor', format: 'money' },
    { key: 'description', label: 'Descripción' },
    { key: 'created_at', label: 'Fecha', format: 'datetime' },
  ],
  fields: [
    { key: 'cash_session_id', label: 'UUID de sesión', required: true, pathOnly: true },
    {
      key: 'transaction_type',
      label: 'Tipo',
      kind: 'select',
      options: transactionTypeOptions,
      required: true,
    },
    {
      key: 'source',
      label: 'Origen',
      kind: 'select',
      options: sourceOptions,
      defaultValue: 'manual',
    },
    { key: 'amount', label: 'Valor', kind: 'number', required: true },
    { key: 'reference', label: 'Referencia' },
    { key: 'description', label: 'Descripción', required: true },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const supplierResource: ResourceDefinition = {
  key: 'suppliers',
  title: 'Proveedores',
  singular: 'proveedor',
  icon: 'mdi-truck-delivery-outline',
  description: 'Directorio de proveedores y datos comerciales.',
  listPath: '/suppliers',
  createPath: '/suppliers',
  updatePath: '/suppliers/{id}',
  updateMethod: 'patch',
  deletePath: '/suppliers/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'tax_id', label: 'Identificación' },
    { key: 'business_name', label: 'Razón social' },
    { key: 'contact_name', label: 'Contacto' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'tax_id', label: 'NIT o identificación', required: true },
    { key: 'business_name', label: 'Razón social', required: true },
    { key: 'trade_name', label: 'Nombre comercial' },
    { key: 'contact_name', label: 'Contacto' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'email', label: 'Correo', kind: 'email' },
    { key: 'address', label: 'Dirección' },
    { key: 'city', label: 'Ciudad' },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const orderResource: ResourceDefinition = {
  key: 'orders',
  title: 'Órdenes',
  singular: 'orden de compra',
  icon: 'mdi-clipboard-list-outline',
  description: 'Órdenes, aprobación, cancelación y seguimiento de recepción.',
  listPath: '/purchases/orders',
  createPath: '/purchases/orders',
  updatePath: '/purchases/orders/{id}',
  updateMethod: 'patch',
  columns: [
    { key: 'order_number', label: 'Orden' },
    { key: 'supplier_name', label: 'Proveedor' },
    { key: 'status', label: 'Estado', format: 'status' },
    { key: 'total_amount', label: 'Total', format: 'money' },
    { key: 'ordered_at', label: 'Fecha', format: 'datetime' },
  ],
  fields: [
    {
      key: 'supplier_id',
      label: 'Proveedor',
      kind: 'select',
      optionsPath: '/suppliers?limit=100&is_active=true',
      optionLabelKeys: ['business_name'],
      required: true,
    },
    { key: 'order_number', label: 'Número de orden', required: true },
    { key: 'expected_at', label: 'Fecha esperada', kind: 'datetime-local' },
    { key: 'tax_amount', label: 'Impuestos', kind: 'number', defaultValue: '0.00' },
    { key: 'discount_amount', label: 'Descuento', kind: 'number', defaultValue: '0.00' },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
    {
      key: 'details',
      label: 'Productos solicitados',
      kind: 'json',
      required: true,
      defaultValue: [{ product_id: '', ordered_quantity: '1.000', unit_cost: '0.00' }],
      help: 'Arreglo con product_id, ordered_quantity y unit_cost.',
      rows: 7,
    },
  ],
  actions: [
    {
      key: 'approve',
      label: 'Aprobar',
      icon: 'mdi-check-circle-outline',
      color: 'success',
      method: 'post',
      path: '/purchases/orders/{id}/approve',
    },
    {
      key: 'cancel',
      label: 'Cancelar',
      icon: 'mdi-cancel',
      color: 'error',
      method: 'post',
      path: '/purchases/orders/{id}/cancel',
      fields: [{ key: 'reason', label: 'Motivo', kind: 'textarea', required: true, rows: 3 }],
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const receiptResource: ResourceDefinition = {
  key: 'receipts',
  title: 'Recepciones',
  singular: 'recepción',
  icon: 'mdi-package-down',
  description: 'Recepción parcial o final y actualización de costos y existencias.',
  listPath: '/purchases/receipts',
  createPath: '/purchases/orders/{order_id}/receipts',
  columns: [
    { key: 'receipt_number', label: 'Recepción' },
    { key: 'purchase_order_id', label: 'Orden' },
    { key: 'supplier_name', label: 'Proveedor' },
    { key: 'total_amount', label: 'Total', format: 'money' },
    { key: 'received_at', label: 'Fecha', format: 'datetime' },
  ],
  fields: [
    { key: 'order_id', label: 'UUID de la orden', required: true, pathOnly: true },
    { key: 'receipt_number', label: 'Número de recepción', required: true },
    { key: 'supplier_invoice_number', label: 'Factura del proveedor' },
    { key: 'tax_amount', label: 'Impuestos', kind: 'number', defaultValue: '0.00' },
    { key: 'discount_amount', label: 'Descuento', kind: 'number', defaultValue: '0.00' },
    { key: 'notes', label: 'Notas', kind: 'textarea', rows: 2 },
    {
      key: 'details',
      label: 'Detalles recibidos',
      kind: 'json',
      required: true,
      defaultValue: [{ purchase_order_detail_id: '', quantity: '1.000', unit_cost: null }],
      help: 'Use el UUID del detalle de la orden y la cantidad recibida.',
      rows: 7,
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const companyResource: ResourceDefinition = {
  key: 'companies',
  title: 'Empresas',
  singular: 'empresa',
  icon: 'mdi-domain',
  description: 'Información legal y de contacto de las empresas.',
  listPath: '/companies',
  updatePath: '/companies/{id}',
  updateMethod: 'put',
  columns: [
    { key: 'name', label: 'Empresa' },
    { key: 'tax_id', label: 'NIT' },
    { key: 'email', label: 'Correo' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'name', label: 'Nombre', required: true },
    { key: 'tax_id', label: 'NIT', required: true },
    { key: 'email', label: 'Correo', kind: 'email' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'is_active', label: 'Activa', kind: 'switch', defaultValue: true, editOnly: true },
  ],
}

const employeeResource: ResourceDefinition = {
  key: 'employees',
  title: 'Empleados',
  singular: 'empleado',
  icon: 'mdi-account-tie-outline',
  description: 'Personal, cargo, compensación, biometría y servicios asociados.',
  listPath: '/employees',
  createPath: '/employees',
  updatePath: '/employees/{id}',
  updateMethod: 'put',
  deletePath: '/employees/{id}',
  deleteLabel: 'Desactivar',
  companyQueryKey: 'company_id',
  columns: [
    { key: 'first_name', label: 'Nombres' },
    { key: 'last_name', label: 'Apellidos' },
    { key: 'job_title', label: 'Cargo' },
    { key: 'email', label: 'Correo' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'first_name', label: 'Nombres', required: true },
    { key: 'last_name', label: 'Apellidos', required: true },
    { key: 'document_number', label: 'Documento' },
    { key: 'email', label: 'Correo', kind: 'email' },
    { key: 'phone', label: 'Teléfono' },
    { key: 'job_title', label: 'Cargo', required: true },
    { key: 'salary', label: 'Salario', kind: 'number' },
    { key: 'commission_percentage', label: 'Comisión %', kind: 'number' },
    { key: 'hire_date', label: 'Fecha de contratación', kind: 'date' },
    { key: 'attendance_code', label: 'Código de asistencia' },
    { key: 'biometric_device_user_id', label: 'ID biométrico' },
    { key: 'biometric_enabled', label: 'Biometría activa', kind: 'switch', defaultValue: false },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
    { key: 'company_id', label: 'Empresa', companyFromSession: true, createOnly: true },
    {
      key: 'service_ids',
      label: 'UUID de servicios',
      kind: 'json',
      defaultValue: [],
      help: 'Arreglo de UUID de servicios que puede prestar.',
      rows: 4,
    },
  ],
  defaultQuery: { skip: 0, limit: 100 },
}

const userResource: ResourceDefinition = {
  key: 'users',
  title: 'Usuarios',
  singular: 'usuario',
  icon: 'mdi-account-key-outline',
  description: 'Cuentas de acceso, verificación y activación.',
  listPath: '/users',
  createPath: '/users',
  updatePath: '/users/{id}',
  updateMethod: 'put',
  deletePath: '/users/{id}',
  deleteLabel: 'Desactivar',
  columns: [
    { key: 'email', label: 'Correo' },
    { key: 'is_active', label: 'Activo', format: 'boolean' },
    { key: 'is_verified', label: 'Verificado', format: 'boolean' },
    { key: 'created_at', label: 'Creado', format: 'datetime' },
  ],
  fields: [
    { key: 'company_id', label: 'Empresa', companyFromSession: true, createOnly: true },
    { key: 'email', label: 'Correo', kind: 'email', required: true },
    { key: 'password', label: 'Contraseña', kind: 'password', required: true, createOnly: true },
    { key: 'password', label: 'Nueva contraseña', kind: 'password', editOnly: true },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true, editOnly: true },
    {
      key: 'is_verified',
      label: 'Verificado',
      kind: 'switch',
      defaultValue: false,
      editOnly: true,
    },
  ],
  actions: [
    {
      key: 'assign-role',
      label: 'Asignar rol',
      icon: 'mdi-shield-account-outline',
      method: 'post',
      path: '/roles/assign-user',
      itemIdPayloadKey: 'user_id',
      fields: [{ key: 'role_id', label: 'UUID del rol', required: true }],
    },
  ],
}

const roleResource: ResourceDefinition = {
  key: 'roles',
  title: 'Roles',
  singular: 'rol',
  icon: 'mdi-shield-account-outline',
  description: 'Roles empresariales y permisos asignados.',
  listPath: '/roles/company/{company_id}',
  createPath: '/roles',
  updatePath: '/roles/{id}',
  updateMethod: 'put',
  deletePath: '/roles/{id}',
  deleteLabel: 'Eliminar',
  protectedFlagKey: 'is_system_role',
  columns: [
    { key: 'name', label: 'Rol' },
    { key: 'description', label: 'Descripción' },
    { key: 'is_system_role', label: 'Sistema', format: 'boolean' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'company_id', label: 'Empresa', companyFromSession: true, createOnly: true },
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 2 },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
    { key: 'permission_ids', label: 'UUID de permisos', kind: 'json', defaultValue: [], rows: 4 },
  ],
  actions: [
    {
      key: 'assign-permission',
      label: 'Asignar permiso',
      icon: 'mdi-shield-key-outline',
      method: 'post',
      path: '/roles/assign-permission',
      itemIdPayloadKey: 'role_id',
      fields: [{ key: 'permission_id', label: 'UUID del permiso', required: true }],
    },
  ],
}

const permissionResource: ResourceDefinition = {
  key: 'permissions',
  title: 'Permisos',
  singular: 'permiso',
  icon: 'mdi-shield-key-outline',
  description: 'Catálogo global de permisos RBAC.',
  listPath: '/permissions',
  readOnly: true,
  columns: [
    { key: 'name', label: 'Permiso' },
    { key: 'description', label: 'Descripción' },
    { key: 'is_active', label: 'Estado', format: 'boolean' },
  ],
  fields: [
    { key: 'name', label: 'Nombre', required: true },
    { key: 'description', label: 'Descripción', kind: 'textarea', rows: 2 },
    { key: 'is_active', label: 'Activo', kind: 'switch', defaultValue: true },
  ],
}

const auditResource: ResourceDefinition = {
  key: 'audit',
  title: 'Auditoría',
  singular: 'registro',
  icon: 'mdi-clipboard-text-clock-outline',
  description: 'Trazabilidad de acciones, entidad afectada y resultado.',
  listPath: '/audit/',
  readOnly: true,
  columns: [
    { key: 'created_at', label: 'Fecha', format: 'datetime' },
    { key: 'module', label: 'Módulo' },
    { key: 'action', label: 'Acción' },
    { key: 'entity_type', label: 'Entidad' },
    { key: 'success', label: 'Resultado', format: 'boolean' },
  ],
  fields: [],
  defaultQuery: { limit: 100 },
}

export const operationModules: ModuleDefinition[] = [
  {
    key: 'customers-services',
    title: 'Clientes y servicios',
    subtitle: 'Relaciones comerciales y catálogo de atención.',
    icon: 'mdi-account-heart-outline',
    sprint: 'Operación integrada',
    resources: [customerResource, serviceResource],
  },
  {
    key: 'sales-pos',
    title: 'Ventas y POS',
    subtitle: 'Ventas mixtas, pagos y comprobantes internos.',
    icon: 'mdi-point-of-sale',
    sprint: 'Operación integrada',
    resources: [salesResource],
  },
  {
    key: 'inventory',
    title: 'Inventario',
    subtitle: 'Categorías, productos, existencias y movimientos.',
    icon: 'mdi-warehouse',
    sprint: 'Operación integrada',
    resources: [categoryResource, productResource, movementResource],
  },
  {
    key: 'cash-register',
    title: 'Caja',
    subtitle: 'Cajas, sesiones, arqueo y transacciones.',
    icon: 'mdi-cash-register',
    sprint: 'Operación integrada',
    resources: [registerResource, sessionResource, transactionResource],
  },
  {
    key: 'purchases',
    title: 'Compras y proveedores',
    subtitle: 'Abastecimiento, órdenes y recepción de mercancía.',
    icon: 'mdi-cart-arrow-down',
    sprint: 'Operación integrada',
    resources: [supplierResource, orderResource, receiptResource],
  },
  {
    key: 'administration',
    title: 'Administración',
    subtitle: 'Empresa, personal, accesos, RBAC y auditoría.',
    icon: 'mdi-cog-outline',
    sprint: 'Operación integrada',
    resources: [
      companyResource,
      employeeResource,
      userResource,
      roleResource,
      permissionResource,
      auditResource,
    ],
  },
]

export function getOperationModule(key: string): ModuleDefinition | undefined {
  return operationModules.find((module) => module.key === key)
}
